version: 0.2

phases:
  install:
    runtime-versions:
      docker : 19
      
  pre_build:
    commands:
      - echo Current Build number is v${CODEBUILD_BUILD_NUMBER}
      - echo Loggin in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region us-west-1)
      
  build:
    commands:
      - echo Build started on date
      - echo Building the Docker image...
      - chmod +x gradlew
      - ./gradlew bootBuildImage --imageName=testBootApp
      - docker tag testBootApp:latest public.ecr.aws/w1k0v2l5/foodtruck-test/testBootApp:v${CODEBUILD_BUILD_NUMBER}
      
  post_build:
    commands:
      - echo Build completed on date
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/w1k0v2l5/foodtruck-test/testBootApp:v${CODEBUILD_BUILD_NUMBER}
      - echo Writing image definitions file...
      - printf '[{"name":"testBootApp","imageUri":"%s"}]' public.ecr.aws/w1k0v2l5/foodtruck-test/testBootApp:v${CODEBUILD_BUILD_NUMBER} > imagedefinitions.json
      - echo cat imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
