version: 0.2

phases:
  install:
    runtime-versions:
      docker : 19
      
  pre_build:
    commands:
      - REGION=us-west-1
      - REPOSITORY_URI=515408504552.dkr.ecr.us-west-1.amazonaws.com/foodtruck
      - IMAGE_NAME=testBootApp
      - echo Current Build number is v${CODEBUILD_BUILD_NUMBER}
      - echo Loggin in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $REGION | docker login -u AWS --password-stdin $REPOSITORY_URI
      
  build:
    commands:
      - echo Build started on date
      - echo Building the Docker image...
      - chmod +x gradlew
      - ./gradlew bootBuildImage --imageName=$IMAGE_NAME
      - docker tag $IMAGE_NAME:latest $REPOSITORY_URI/$IMAGE_NAME:v${CODEBUILD_BUILD_NUMBER}
      
  post_build:
    commands:
      - echo Build completed on date
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI/$IMAGE_NAME:v${CODEBUILD_BUILD_NUMBER}
      - echo Writing image definitions file...
      - printf '[{"name":"testBootApp","imageUri":"%s"}]' $REPOSITORY_URI/$IMAGE_NAME:v${CODEBUILD_BUILD_NUMBER} > imagedefinitions.json
      - echo cat imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
