version: 0.2

phases:
  install:
    runtime-versions:
      docker : 19
      
  pre_build:
    commands:
      - REGION=ap-northeast-2
      - REPOSITORY_URI=844148244640.dkr.ecr.ap-northeast-2.amazonaws.com/foodtruck
      - IMAGE_NAME=testBootApp
      - echo Current Build number is v${CODEBUILD_BUILD_NUMBER}
      - echo Loggin in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 844148244640.dkr.ecr.ap-northeast-2.amazonaws.com/foodtruck
      
  build:
    commands:
      - echo Build started on date
      - echo Building the Docker image...
      - chmod +x gradlew
      - ./gradlew bootBuildImage --imageName=testBootApp
      - docker tag testBootApp:latest $REPOSITORY_URI/testBootApp:v${CODEBUILD_BUILD_NUMBER}
      
  post_build:
    commands:
      - echo Build completed on date
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI/testBootApp:v${CODEBUILD_BUILD_NUMBER}
      - echo Writing image definitions file...
      - printf '[{"name":"testBootApp","imageUri":"%s"}]' $REPOSITORY_URI/testBootApp:v${CODEBUILD_BUILD_NUMBER} > imagedefinitions.json
      - echo cat imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
