version: 0.2

phases:
  install:
    runtime-versions:
      docker : 19
      
  pre_build:
    commands:
      - echo Current Build number is v${CODEBUILD_BUILD_NUMBER}
      - echo Loggin in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 844148244640.dkr.ecr.ap-northeast-2.amazonaws.com
      
  build:
    commands:
      - echo Build started on date
      - echo Building the Docker image...
      - chmod +x gradlew
      - pwd
      - ./gradlew bootBuildImage --imageName=foodtruck
      - docker tag foodtruck:latest 844148244640.dkr.ecr.ap-northeast-2.amazonaws.com/foodtruck:v${CODEBUILD_BUILD_NUMBER}
      
  post_build:
    commands:
      - echo Build completed on date
      - echo Pushing the Docker image...
      - docker push 844148244640.dkr.ecr.ap-northeast-2.amazonaws.com/foodtruck:v${CODEBUILD_BUILD_NUMBER}
      - echo Writing image definitions file...
      - printf '[{"name":"foodtruck","imageUri":"%s"}]' 844148244640.dkr.ecr.ap-northeast-2.amazonaws.com/foodtruck:v${CODEBUILD_BUILD_NUMBER} > imagedefinitions.json
      - echo cat imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
